name: everyday_chronicles
description: everyday chronicles is an automted personal digitial diary app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  persistent_bottom_nav_bar: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true

  assets:
    - assets/images/app-icon.png
    - assets/images/icon-dark.png
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/images/login_signup_images/
    - assets/images/logo/
    - assets/images/forget_password_images/
