// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzooI_RGpTpipGrLpfzwt-1I-dpwH5ZMU',
    appId: '1:216499647850:android:9aefa9a1119df4f8b5e113',
    messagingSenderId: '216499647850',
    projectId: 'ai-test-project-b4d15',
    storageBucket: 'ai-test-project-b4d15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4RcAihHtikf76Uj6Nxa6Rm3nLhotJOo',
    appId: '1:216499647850:ios:4c3cfae3428883efb5e113',
    messagingSenderId: '216499647850',
    projectId: 'ai-test-project-b4d15',
    storageBucket: 'ai-test-project-b4d15.firebasestorage.app',
    iosBundleId: 'com.example.everydayChronicle',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHl1zvjI-PB-8UmkojCFIwkGvQso--nQI',
    appId: '1:216499647850:web:113f916fad36ab5cb5e113',
    messagingSenderId: '216499647850',
    projectId: 'ai-test-project-b4d15',
    authDomain: 'ai-test-project-b4d15.firebaseapp.com',
    storageBucket: 'ai-test-project-b4d15.firebasestorage.app',
    measurementId: 'G-FJZXPE8H60',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN4RcAihHtikf76Uj6Nxa6Rm3nLhotJOo',
    appId: '1:216499647850:ios:4c3cfae3428883efb5e113',
    messagingSenderId: '216499647850',
    projectId: 'ai-test-project-b4d15',
    storageBucket: 'ai-test-project-b4d15.firebasestorage.app',
    iosBundleId: 'com.example.everydayChronicle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHl1zvjI-PB-8UmkojCFIwkGvQso--nQI',
    appId: '1:216499647850:web:a17e12f9ce33bd39b5e113',
    messagingSenderId: '216499647850',
    projectId: 'ai-test-project-b4d15',
    authDomain: 'ai-test-project-b4d15.firebaseapp.com',
    storageBucket: 'ai-test-project-b4d15.firebasestorage.app',
    measurementId: 'G-7ZZG2XNF70',
  );

}